# Welcome to Serverless!
#
# This file is the main config file for your service.
# For full config options, check the docs:
#    docs.serverless.com
#

# Test LIBND PurlService
service: testlibndpysvc01

# AWS & python Config, with required LIB-ESU ETags
# Notice Profile 'serverless'
# Requires an AWS User Profile named that that has IAM privs fro Serverless
# Development Note: 2.7 may not be the default python
# on newer Mac OS X desktops
provider:
  name: aws
  runtime: python2.7
  stage: dev
  region: us-east-1
  profile: serverless
  stackTags:
    Name: Serverless Test msuhovec
    Environment: dev
    Contact: msuhovec@nd.edu
    Owner: mark suhovecky
    Description: Python Serverless Deploy
    InceptDate: "2017-01-20"

  include:
    - vendored/**

# One handler function, redirect
# On API endpoint
# Uses Contenful.com for Content, and looks at ENV vars
# LIBND_PURLSVC_ID and LIBND_PURLSVC_KEY for the Contentful 
functions:
  redirect:
    handler: handler.redirect
    events:
      - http:
          path: purl/redirect/{code}
          method: get
    environment:
          LIBND_PURL_SVC_ID: ${env:LIBND_PURL_SVC_ID}
          LIBND_PURL_SVC_KEY: ${env:LIBND_PURL_SVC_KEY}

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
